disable-weather-changes: true

disable-physics: false

disable-gravity-physics: false

disable-explosions: true

disable-soil-trample: true

disable-leaves-decay: false

fix-attackspeed: true

iron-trapdoor-interaction: true